serviceAccount:
  create: false
  automountServiceAccountToken: false

automountServiceAccountToken: false

replicas: %KUBERNETES_REPLICA_COUNT%

service:
  port: 3000

podDisruptionBudget:
  enabled: true
  minAvailable: 1

readinessProbe:
  httpGet:
    path: /api/health
    port: grafana
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: grafana
  initialDelaySeconds: 90
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

testFramework:
  enabled: false

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
      
ingress:
  enabled: false

resources:
  requests:
    cpu: %KUBERNETES_CPU_REQUEST%
    memory: %KUBERNETES_MEMORY_REQUEST%
  limits:
    cpu: %KUBERNETES_CPU_LIMIT%
    memory: %KUBERNETES_MEMORY_LIMIT%

nodeSelector:
  kubernetes.io/os: linux
  nodepool.compute: %KUBERNETES_NODEPOOL_COMPUTE%

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: %APP_NAME%

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: %APP_NAME%

persistence:
  enabled: false

admin:
  existingSecret: %APP_NAME%-admin-auth
  userKey: admin-username
  passwordKey: admin-password

extraVolumes:
  - name: tmp
    emptyDir: {}
  - name: var-tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: var-tmp
    mountPath: /var/tmp

extraSecretMounts:
  - name: sql-auth
    secretName: %APP_NAME%-sql-auth
    mountPath: /etc/sql/auth
    readOnly: true
  - name: sql-ca-cert
    secretName: %APP_NAME%-sql-ca-cert
    mountPath: /etc/sql/certs
    readOnly: true
  # - name: smtp-auth
  #   secretName: resend-auth
  #   mountPath: /etc/smtp/auth
  #   readOnly: true

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/"
    protocol: http
    enable_gzip: true
    serve_from_sub_path: false
  plugins:
    preinstall_auto_update: false
  security:
    disable_initial_admin_creation: false
    cookie_secure: true
    cookie_samesite: strict
    strict_transport_security: true
    strict_transport_security_max_age_seconds: 15768000
    strict_transport_security_preload: true
    x_content_type_options: true
    x_xss_protection: true
  database:
    type: %SQL_TYPE%
    host: %SQL_HOST%
    port: %SQL_PORT%
    name: %SQL_NAME%
    user: $__file{/etc/sql/auth/username}
    password: $__file{/etc/sql/auth/password}
    ssl_mode: %SQL_SSL_MODE%
    ca_cert_path: /etc/sql/certs/ca.pem
  analytics:
    reporting_enabled: false
    check_for_updates: false
    check_for_plugin_updates: false
  log:
    mode: console
  users:
    viewers_can_edit: false
    allow_sign_up: false
  auth.anonymous:
    enabled: false
  # smtp:
  #   enabled: true
  #   skip_verify: false
  #   host: $__file{/etc/smtp/auth/host}
  #   from_name: $__file{/etc/smtp/auth/sender-name}
  #   from_address: $__file{/etc/smtp/auth/sender-email}
  #   user: $__file{/etc/smtp/auth/username}
  #   password: $__file{/etc/smtp/auth/apikey}

sidecar:
  resources:
    requests:
      cpu: 25m
      memory: 96Mi 
    limits:
      cpu: 75m
      memory: 288Mi
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  dashboards:
    enabled: false
    searchNamespace: %KUBERNETES_NAMESPACE%
  datasources:
    enabled: false
    searchNamespace: %KUBERNETES_NAMESPACE%

revisionHistoryLimit: 0
