apiVersion: v1
kind: Secret
metadata:
  name: %APP_NAME%-admin-auth
  namespace: %KUBERNETES_NAMESPACE%
type: Opaque
stringData:
  admin-username: %GRAFANA_ADMIN_USERNAME%
  admin-password: %GRAFANA_ADMIN_PASSWORD%